// Tests for ADR-011: Workflow Pipeline Hard-Links
// 1. Gate 0 → Gate 1 context pipe (businessConstraints)
// 2. PRD auto-persist (prd_elicit ensures structured data is not lost)
// 3. State hydration (restoreWorkflowState)
import { describe, it, expect } from 'vitest';
import { analyzeGoal } from '../../src/workflow/understand.js';
import { generateInitialPRD, applyComplaints, type PRDDocument } from '../../src/workflow/prd-elicitation.js';
import { CycleRunner } from '../../src/workflow/cycle-runner.js';
import type { ShellResult } from '../../src/workflow/validate.js';

const PROJECT_ROOT = process.cwd();

function makeMockShell(): (cmd: string, cwd: string) => Promise<ShellResult> {
  return async (cmd: string) => ({
    exitCode: 0,
    stdout: `mock: ${cmd.slice(0, 40)}`,
    stderr: '',
    durationMs: 1,
  });
}

// ═══════════════════════════════════════
// Test Group 1: Gate 0 → Gate 1 Context Pipe
// ADR-011: businessConstraints should flow into PRD's mustNot + context
// ═══════════════════════════════════════

describe('ADR-011: Gate Context Pipe (businessConstraints)', () => {
  it('should inject businessConstraints into mustNot', () => {
    const analysis = analyzeGoal({ goal: '가계부 앱 만들기' });
    const constraints = ['Gate 0 판정: PASS', '사유: 시장 검증 완료', 'ROI 분석: 월 10만원 이상 기대'];

    const prd = generateInitialPRD('가계부 앱 만들기', analysis, undefined, constraints);

    // All business constraints should appear in mustNot
    for (const c of constraints) {
      expect(prd.mustNot).toContain(c);
    }
  });

  it('should inject businessConstraints into context string', () => {
    const analysis = analyzeGoal({ goal: '블로그 플랫폼 구축' });
    const constraints = ['Gate 0 판정: PIVOT', '피봇 제안: B2B로 전환 필요'];

    const prd = generateInitialPRD('블로그 플랫폼 구축', analysis, undefined, constraints);

    expect(prd.context).toContain('비즈니스 Gate 제약사항');
    expect(prd.context).toContain('PIVOT');
    expect(prd.context).toContain('B2B로 전환 필요');
  });

  it('should NOT modify mustNot when businessConstraints is undefined', () => {
    const analysis = analyzeGoal({ goal: '대시보드 만들기' });

    const withConstraints = generateInitialPRD('대시보드 만들기', analysis, undefined, ['제약1']);
    const without = generateInitialPRD('대시보드 만들기', analysis, undefined, undefined);

    // Without constraints: mustNot should only have base safety items
    expect(withConstraints.mustNot.length).toBeGreaterThan(without.mustNot.length);
  });

  it('should NOT modify mustNot when businessConstraints is empty', () => {
    const analysis = analyzeGoal({ goal: '채팅 기능 구현' });

    const withEmpty = generateInitialPRD('채팅 기능 구현', analysis, undefined, []);
    const without = generateInitialPRD('채팅 기능 구현', analysis, undefined, undefined);

    expect(withEmpty.mustNot.length).toBe(without.mustNot.length);
  });

  it('should not duplicate constraints already in mustNot', () => {
    const analysis = analyzeGoal({ goal: '결제 API 구현' });
    // '하드코딩된 API 키 / 비밀번호' is already generated by generateMustNots
    const constraints = ['하드코딩된 API 키 / 비밀번호', '새로운 제약'];

    const prd = generateInitialPRD('결제 API 구현', analysis, undefined, constraints);

    const apiKeyCount = prd.mustNot.filter(m => m === '하드코딩된 API 키 / 비밀번호').length;
    expect(apiKeyCount).toBe(1); // no duplicate
    expect(prd.mustNot).toContain('새로운 제약');
  });

  it('should combine projectContext and businessConstraints together', () => {
    const analysis = analyzeGoal({ goal: '게시판 기능 추가' });
    const constraints = ['타겟: B2B 고객'];

    const prd = generateInitialPRD('게시판 기능 추가', analysis, '기존 Next.js 프로젝트', constraints);

    expect(prd.context).toContain('Next.js');
    expect(prd.context).toContain('비즈니스 Gate 제약사항');
    expect(prd.context).toContain('타겟: B2B 고객');
  });
});

// ═══════════════════════════════════════
// Test Group 2: PRD Structure Preservation
// ADR-011: PRD document retains all fields after business constraint injection
// ═══════════════════════════════════════

describe('ADR-011: PRD Structure Preservation', () => {
  it('should preserve all PRD sections after constraint injection', () => {
    const analysis = analyzeGoal({ goal: '프론트엔드 대시보드 만들기' });
    const constraints = ['Gate 0 판정: PASS', 'CEO: ROI 적합'];

    const prd = generateInitialPRD('프론트엔드 대시보드 만들기', analysis, undefined, constraints);

    // All standard sections must exist
    expect(prd.context).toBeTruthy();
    expect(prd.scope).toBeInstanceOf(Array);
    expect(prd.nonGoals).toBeInstanceOf(Array);
    expect(prd.mustHave).toBeInstanceOf(Array);
    expect(prd.shouldHave).toBeInstanceOf(Array);
    expect(prd.mustNot).toBeInstanceOf(Array);
    expect(prd.successCriteria).toBeInstanceOf(Array);
    expect(prd.risks).toBeInstanceOf(Array);
    expect(prd.version).toBe(0);
  });

  it('should retain injected constraints after applyComplaints refinement', () => {
    const analysis = analyzeGoal({ goal: '결제 시스템 구현' });
    const constraints = ['월매출 목표 100만원', 'PG사 심사 필수'];

    const prd = generateInitialPRD('결제 시스템 구현', analysis, undefined, constraints);

    // Simulate customer review with blockers
    const refined = applyComplaints(prd, [
      {
        personaId: 'user-advocate',
        personaName: 'User Advocate',
        verdict: 'REJECTED',
        blockers: ['핵심 기능 3클릭 이내 기준이 성공 기준에 없습니다'],
        wishes: [],
        approvedAspects: [],
      },
    ]);

    // Original constraints should survive the refinement
    expect(refined.mustNot).toContain('월매출 목표 100만원');
    expect(refined.mustNot).toContain('PG사 심사 필수');
    // New criterion should also be added
    expect(refined.successCriteria.some(c => c.includes('3클릭'))).toBe(true);
    // Version incremented
    expect(refined.version).toBe(1);
  });
});

// ═══════════════════════════════════════
// Test Group 3: CycleRunner State Hydration
// ADR-011: restoreWorkflowState should return null for fresh runs (no Obsidian)
// ═══════════════════════════════════════

describe('ADR-011: CycleRunner State Hydration', () => {
  it('should return null when no ObsidianStore is provided', async () => {
    const runner = new CycleRunner({
      maxRetries: 1,
      projectRoot: PROJECT_ROOT,
      runShell: makeMockShell(),
      // No obsidianStore
    });

    const result = await runner.restoreWorkflowState('테스트 목표');
    expect(result).toBeNull();
  });

  it('should return null when ObsidianStore readNote throws (file not found)', async () => {
    const mockStore = {
      readNote: async () => { throw new Error('404 Not Found'); },
      writeNote: async () => {},
      searchNotes: async () => [],
      listNotes: async () => [],
      deleteNote: async () => {},
    };

    const runner = new CycleRunner({
      maxRetries: 1,
      projectRoot: PROJECT_ROOT,
      runShell: makeMockShell(),
      obsidianStore: mockStore as any,
    });

    const result = await runner.restoreWorkflowState('존재하지 않는 목표');
    expect(result).toBeNull();
  });

  it('should return null when readNote returns empty content', async () => {
    const mockStore = {
      readNote: async () => ({ content: '', frontmatter: {} }),
      writeNote: async () => {},
      searchNotes: async () => [],
      listNotes: async () => [],
      deleteNote: async () => {},
    };

    const runner = new CycleRunner({
      maxRetries: 1,
      projectRoot: PROJECT_ROOT,
      runShell: makeMockShell(),
      obsidianStore: mockStore as any,
    });

    const result = await runner.restoreWorkflowState('빈 상태');
    expect(result).toBeNull();
  });

  it('should restore state when valid frontmatter exists', async () => {
    const mockStore = {
      readNote: async () => ({
        content: '# Workflow State: 테스트',
        frontmatter: {
          type: 'workflow_state',
          status: 'prototyping',
          completedStages: ['understand', 'gate0', 'gate1'],
        },
      }),
      writeNote: async () => {},
      searchNotes: async () => [],
      listNotes: async () => [],
      deleteNote: async () => {},
    };

    const runner = new CycleRunner({
      maxRetries: 1,
      projectRoot: PROJECT_ROOT,
      runShell: makeMockShell(),
      obsidianStore: mockStore as any,
    });

    const result = await runner.restoreWorkflowState('테스트 목표');
    expect(result).not.toBeNull();
    expect(result!.lastStage).toBe('gate1');
    expect(result!.completedStages).toEqual(['understand', 'gate0', 'gate1']);
  });

  it('should return null when completedStages is empty', async () => {
    const mockStore = {
      readNote: async () => ({
        content: '# Workflow State',
        frontmatter: {
          type: 'workflow_state',
          status: 'idle',
          completedStages: [],
        },
      }),
      writeNote: async () => {},
      searchNotes: async () => [],
      listNotes: async () => [],
      deleteNote: async () => {},
    };

    const runner = new CycleRunner({
      maxRetries: 1,
      projectRoot: PROJECT_ROOT,
      runShell: makeMockShell(),
      obsidianStore: mockStore as any,
    });

    const result = await runner.restoreWorkflowState('빈 스테이지');
    expect(result).toBeNull();
  });

  it('should handle malformed frontmatter gracefully (non-array completedStages)', async () => {
    const mockStore = {
      readNote: async () => ({
        content: '# Workflow State',
        frontmatter: {
          type: 'workflow_state',
          status: 'complete',
          completedStages: 'not-an-array', // <-- malformed
        },
      }),
      writeNote: async () => {},
      searchNotes: async () => [],
      listNotes: async () => [],
      deleteNote: async () => {},
    };

    const runner = new CycleRunner({
      maxRetries: 1,
      projectRoot: PROJECT_ROOT,
      runShell: makeMockShell(),
      obsidianStore: mockStore as any,
    });

    const result = await runner.restoreWorkflowState('잘못된 데이터');
    // Should not crash — returns null because completedStages is invalid
    expect(result).toBeNull();
  });

  it('should filter non-string entries from completedStages', async () => {
    const mockStore = {
      readNote: async () => ({
        content: '# Workflow State',
        frontmatter: {
          type: 'workflow_state',
          status: 'validating',
          completedStages: ['understand', 42, null, 'gate0', undefined], // mixed types
        },
      }),
      writeNote: async () => {},
      searchNotes: async () => [],
      listNotes: async () => [],
      deleteNote: async () => {},
    };

    const runner = new CycleRunner({
      maxRetries: 1,
      projectRoot: PROJECT_ROOT,
      runShell: makeMockShell(),
      obsidianStore: mockStore as any,
    });

    const result = await runner.restoreWorkflowState('혼합 타입');
    expect(result).not.toBeNull();
    expect(result!.completedStages).toEqual(['understand', 'gate0']); // only strings
    expect(result!.lastStage).toBe('gate0');
  });
});
